### ISSUE TITLE
how to use 4-bit quantization?

### ISSUE THREAD

**Issue by kingsdom-sk** [lum3on/comfyui_HiDream-Sampler#1]
how to use 4-bit quantization?
No option in nodes, and models  download in full mode by default.

**Comment by AIENGI** [comment]
yeah no clue either. It's using over 27gb vram for me by default but the description says 12gb is fine? Lol.

**Comment by benjamin-bertram** [comment]
Do you use the newest version of diffusers and transformers?
4Bit is in use via their libraries

`from transformers import BitsAndBytesConfig as TransformersBitsAndBytesConfig
from diffusers import BitsAndBytesConfig as DiffusersBitsAndBytesConfig`

**Comment by kingsdom-sk** [comment]
> Do you use the newest version of diffusers and transformers? 4Bit is in use via their libraries
> 
> `from transformers import BitsAndBytesConfig as TransformersBitsAndBytesConfig from diffusers import BitsAndBytesConfig as DiffusersBitsAndBytesConfig`

all my package here:
Package                   Version
------------------------- ------------------
absl-py                   2.2.1
accelerate                1.5.2
addict                    2.4.0
aiofiles                  23.2.1
aiohappyeyeballs          2.6.1
aiohttp                   3.11.14
aiosignal                 1.3.2
albucore                  0.0.23
albumentations            2.0.5
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
anyio                     4.9.0
attrs                     25.3.0
av                        14.2.0
bitsandbytes              0.45.5
certifi                   2025.1.31
cffi                      1.17.1
chardet                   5.2.0
charset-normalizer        3.4.1
click                     8.1.8
clip-interrogator         0.6.0
color-matcher             0.5.0
colorama                  0.4.6
coloredlogs               15.0.1
colorlog                  6.9.0
comfyui_frontend_package  1.14.5
contourpy                 1.3.1
cryptography              44.0.2
cssselect2                0.8.0
cycler                    0.12.1
ddt                       1.7.2
decorator                 5.2.1
Deprecated                1.2.18
diffusers                 0.33.0.dev0
docutils                  0.21.2
einops                    0.8.1
fastapi                   0.115.12
ffmpy                     0.5.0
filelock                  3.18.0
flash_attn                2.7.4.post1
flatbuffers               25.2.10
fonttools                 4.56.0
frozenlist                1.5.0
fsspec                    2025.3.0
ftfy                      6.3.1
fvcore                    0.1.5.post20221221
gguf                      0.14.0
gitdb                     4.0.12
GitPython                 3.1.44
gradio                    5.23.2
gradio_client             1.8.0
groovy                    0.1.2
h11                       0.14.0
httpcore                  1.0.7
httpx                     0.28.1
huggingface-hub           0.29.3
humanfriendly             10.0
idna                      3.10
imageio                   2.37.0
imageio-ffmpeg            0.6.0
importlib_metadata        8.6.1
iopath                    0.1.10
jax                       0.5.3
jaxlib                    0.5.3
Jinja2                    3.1.6
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
kiwisolver                1.4.8
kornia                    0.8.0
kornia_rs                 0.1.8
lark                      1.2.2
lazy_loader               0.4
lxml                      5.3.1
manifold3d                3.0.1
mapbox_earcut             1.0.3
markdown-it-py            3.0.0
MarkupSafe                3.0.2
matplotlib                3.10.1
matrix-client             0.4.0
mdurl                     0.1.2
mediapipe                 0.10.21
ml_dtypes                 0.5.1
moviepy                   2.1.2
mpmath                    1.3.0
mss                       10.0.0
multidict                 6.2.0
networkx                  3.4.2
numpy                     1.26.4
omegaconf                 2.3.0
onnxruntime               1.21.0
open_clip_torch           2.31.0
opencv-contrib-python     4.11.0.86
opencv-python             4.11.0.86
opencv-python-headless    4.11.0.86
opt_einsum                3.4.0
orjson                    3.10.16
packaging                 24.2
pandas                    2.2.3
peft                      0.15.1
pillow                    10.4.0
pip                       25.0.1
platformdirs              4.3.7
portalocker               3.1.1
proglog                   0.1.10
propcache                 0.3.0
protobuf                  4.25.6
psutil                    5.9.8
pycollada                 0.9
pycparser                 2.22
pydantic                  2.11.0
pydantic_core             2.33.0
pydub                     0.25.1
pygit2                    1.17.0
PyGithub                  2.6.1
Pygments                  2.19.1
PyJWT                     2.10.1
PyNaCl                    1.5.0
pyparsing                 3.2.3
pyreadline3               3.5.4
python-dateutil           2.9.0.post0
python-dotenv             1.1.0
python-multipart          0.0.20
pytz                      2025.2
pywin32                   310
PyYAML                    6.0.2
referencing               0.36.2
regex                     2024.11.6
reportlab                 4.3.1
requests                  2.32.3
rich                      13.9.4
rpds-py                   0.24.0
rtree                     1.4.0
ruff                      0.11.2
safehttpx                 0.1.6
safetensors               0.5.3
sageattention             2.1.1
sageattention             2.1.1
scikit-image              0.25.2
scikit-learn              1.6.1
scipy                     1.15.2
semantic-version          2.10.0
sentencepiece             0.2.0
setuptools                78.1.0
shapely                   2.0.7
shellingham               1.5.4
simsimd                   6.2.1
six                       1.17.0
smmap                     5.0.2
sniffio                   1.3.1
sounddevice               0.5.1
soundfile                 0.13.1
spaces                    0.34.1
spandrel                  0.4.1
starlette                 0.46.1
stringzilla               3.12.3
svg.path                  6.3
svglib                    1.5.1
sympy                     1.13.1
tabulate                  0.9.0
termcolor                 2.5.0
threadpoolctl             3.6.0
tifffile                  2025.3.13
timm                      1.0.15
tinycss2                  1.4.0
tokenizers                0.21.1
toml                      0.10.2
tomlkit                   0.13.2
torch                     2.6.0+cu126
torchaudio                2.6.0+cu126
torchsde                  0.2.6
torchvision               0.21.0+cu126
tqdm                      4.67.1
trampoline                0.1.2
transformers              4.50.0
trimesh                   4.6.5
triton-windows            3.2.0.post17
typer                     0.15.2
typing_extensions         4.12.2
typing-inspection         0.4.0
tzdata                    2025.2
urllib3                   1.26.20
uv                        0.6.10
uvicorn                   0.34.0
vhacdx                    0.0.8.post2
wcwidth                   0.2.13
webencodings              0.5.1
websockets                15.0.1
wrapt                     1.17.2
xatlas                    0.0.9
xxhash                    3.5.0
yacs                      0.1.8
yapf                      0.43.0
yarl                      1.18.3
zipp                      3.21.0

and how to do ?

**Comment by benjamin-bertram** [comment]
I see. Then its really the basemodels, they are not yet quantized. I'll update the node with the quantized models directly from https://github.com/hykilpikonna/HiDream-I1-nf4
I'll try it to implemente tonight

**Comment by benjamin-bertram** [comment]
@kingsdom-sk should be solved now

**Comment by kingsdom-sk** [comment]
thanks for solving problem. But new problem appears.
I can't pip install AutoGPTQ.  I tried much method, still not.
and I found  AutoGPTQ has stopped development and Switch to https://github.com/ModelCloud/GPTQModel
waiting for your solving.
