### ISSUE TITLE
No nf4 versions

### ISSUE THREAD

**Issue by EddieGithub26** [lum3on/comfyui_HiDream-Sampler#10]
The nf4 versions don't appear

![Image](https://github.com/user-attachments/assets/af7842f1-0fcb-4afb-9dc4-57e49026d2e5)

**Comment by EddieGithub26** [comment]
This is the issue I think

![Image](https://github.com/user-attachments/assets/1b81743b-2c9b-4615-a608-76cf71949c32)

**Comment by EddieGithub26** [comment]
This is the issue I think

![Image](https://github.com/user-attachments/assets/5926c699-7cec-4e44-b695-f0e61192d38b)

**Comment by zpengcom** [comment]
![Image](https://github.com/user-attachments/assets/f57dc2a9-64d8-46ee-b956-4bea40795e0b)

**Comment by benjamin-bertram** [comment]
I pushed a bunch of updates – please do a git pull and see if this solves your issue

**Comment by Burgstall-labs** [comment]
![Image](https://github.com/user-attachments/assets/c4a1e8d9-5dbb-471d-9bf9-a9a80bb56274) for me the nf4 are still not showing

**Comment by zpengcom** [comment]
After git pull

![Image](https://github.com/user-attachments/assets/d8a6d08b-0213-4c81-b101-b49fbe908b03)

**Comment by benjamin-bertram** [comment]
Thanks. Can you post the full initializing text from your terminal?

**Comment by benjamin-bertram** [comment]
okay. should have added to do git pull and reinstall the requirements

`git pull`
`pip install -r requirements.txt`
